name: Build firmware

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run
      - name: Get Release Version
        id: get_release_info
        shell: bash
        run: |
          value=`cat tools/version`
          echo ::set-output name=version::$value
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/UZG-01.bin
            bin/UZG-01_v${{ steps.get_release_info.outputs.version }}.full.bin

      - name: Updare version
        run: |
          sed -r 's/v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/v${{ steps.get_release_info.outputs.version }}/g' manifest.json > new.manifest.json
      - name: Read old file
        run: |
          cat manifest.json
      - name: MV file
        run: |
          mv -f new.manifest.json manifest.json 
      - name: Read new file
        run: |
          cat manifest.json
      - name: Commit and push the file
        uses: maxgfr/github-commit-push-file@main
        with:
          commit_name: 'bot: update-manifest.json'