name: Build

on:
  workflow_dispatch:
  push:
    #tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO Project
        run: pio run
      - name: Get version
        run: VERSION=$( cat tools/version )
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/UZG-01.bin
            bin/UZG-01_v${{ env.VERSION }}.full.bin