name: 'update-manifest.json'

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      
      - name: Get Latest Release
        id: get_latest_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: edit file
        run: |
          sed -r 's/v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/v0.1.3/g' manifest.json > new.manifest.json
      - name: read old file
        run: |
          cat manifest.json
      - name: mv file
        run: |
          mv -f new.manifest.json manifest.json 
      - name: read new file
        run: |
          cat manifest.json
      - name: Commit and push the file
        uses: maxgfr/github-commit-push-file@main
        with:
          commit_name: 'bot: update-manifest.json'