name: Build, release, push

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
    tags:
      - '*' # Push events to matching *, any

jobs:
  build_release_push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio==6.1.11

      - name: Build PlatformIO Project
        run: pio run

      - name: Get Release Version
        id: get_version
        shell: bash
        run: |
          value=$(grep '#define VERSION' src/version.h | awk -F '"' '{print $2}')
          echo "version=$value" >> $GITHUB_OUTPUT

      - name: Get last commit message
        id: get_commit_message
        run: |
          currentTag=${GITHUB_REF#refs/tags/}
          badgeText=$'![GitHub Downloads](https://img.shields.io/github/downloads/xyzroe/XZG/'"$currentTag"'/total)\n\n'
          commitMessage=$(git log -1 --pretty=%B | tail -n +2)
          fullCommitMessage="$badgeText$commitMessage"
          echo "commitMessage<<EOF" >> $GITHUB_ENV
          echo "$fullCommitMessage" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Calculate SHA-256 hash of the firmware
        id: sha256_hash
        run: |
          echo "sha256=$(sha256sum bin/XZG_${{ steps.get_version.outputs.version }}.full.bin | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Get size of the firmware
        id: firmware_size
        run: |
          echo "size=$(stat -c %s bin/XZG_${{ steps.get_version.outputs.version }}.full.bin)" >> $GITHUB_OUTPUT

      - name: Create manifest.json for ESP Web Tools
        run: |
          cat << EOF > manifest.json
          {
            "name": "XZG Firmware",
            "version": "${{ steps.get_version.outputs.version }}",
            "files": [
              {
                "path": "XZG_${{ steps.get_version.outputs.version }}.full.bin",
                "type": "app",
                "lzma": false,
                "address": "0x0",
                "sha256": "${{ steps.sha256_hash.outputs.sha256 }}",
                "size": ${{ steps.firmware_size.outputs.size }},
                "url": "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version }}/XZG_${{ steps.get_version.outputs.version }}.full.bin"
              }
            ],
            "chipFamily": "ESP32"
          }
          EOF
          echo "Manifest file created."

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: false
          name: "${{ steps.get_version.outputs.version }}"
          body: ${{ env.commitMessage }}
          files: |
            bin/XZG_${{ steps.get_version.outputs.version }}.ota.bin
            bin/XZG_${{ steps.get_version.outputs.version }}.full.bin
            manifest.json
